# Generated by Django 5.1 on 2024-09-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
